name: Build

on:
  - pull_request
  - push

jobs:
  windows-32:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v1.3.1
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -G "Visual Studio 17 2022" -A Win32 .
      - name: Build
        run: msbuild.exe c-reusables.sln /p:Configuration=Debug /p:Platform=Win32

  windows-64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v1.3.1
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -G "Visual Studio 17 2022" -A x64 .
      - name: Build
        run: msbuild.exe c-reusables.sln /p:Configuration=Debug /p:Platform=x64
